customer_list:
  path: /api/v1/customers
  controller: App\Controller\CustomerController:indexAction
  methods: [GET]
customer_create:
  path: /api/v1/customers
  controller: App\Controller\CustomerController:createAction
  methods: [POST]

product_list:
  path: /api/v1/products
  controller: App\Controller\ProductController:indexAction
  methods: [GET]
product_create:
  path: /api/v1/products
  controller: App\Controller\ProductController:createAction
  methods: [POST]
  requirements:
    id: '\d+'

cart_list:
  path: /api/v1/customers/{id}/card
  controller: App\Controller\CardController:showAction
  methods: [GET]
cart_create:
  path: /api/v1/customers/card
  controller: App\Controller\CardController:createAction
  methods: [POST]
